# Generated by Django 4.1 on 2022-08-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('unique_card_num', models.CharField(default='6054', max_length=4)),
                ('routing_num', models.CharField(default='90294', max_length=5)),
                ('account_num', models.CharField(default='1673641', max_length=7)),
            ],
        ),
    ]
