# Generated by Django 4.1 on 2022-08-29 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_approval_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_birth',
            field=models.CharField(default='1945', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_num',
            field=models.CharField(default='3636740', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='routing_num',
            field=models.CharField(default='64693', max_length=5),
        ),
    ]
